repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - args:
          - --maxkb=2000
        id: check-added-large-files
      - id: detect-private-key
      - id: check-docstring-first
      - id: debug-statements
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: sort-simple-yaml
      - id: check-yaml
      - args:
          - --pytest-test-first
        id: name-tests-test
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
  - hooks:
      - args:
          - --all
        id: pycln
    repo: https://github.com/hadialqattan/pycln
    rev: v2.1.1
  - hooks:
      - id: black
    repo: https://github.com/ambv/black
    rev: 22.10.0
  - hooks:
      - additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-mutable
          - flake8-print
          - flake8-simplify
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 5.0.4
  - hooks:
      - args:
          - -iii
          - -ll
        id: bandit
    repo: https://github.com/pycqa/bandit
    rev: 1.7.4
  - hooks:
      - additional_dependencies:
          - fastapi
          - uvicorn
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
  - hooks:
      - id: isort
    repo: https://github.com/pycqa/isort
    rev: 5.10.1
  - hooks:
      - args:
          - --py3-plus
          - --py36-plus
          - --py37-plus
          - --py38-plus
          - --py39-plus
          - --py310-plus
          - --py311-plus
        id: pyupgrade
    repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
  - hooks:
      - id: hadolint
    repo: https://github.com/AleksaC/hadolint-py
    rev: v2.10.0
  - hooks:
      - additional_dependencies:
          - eslint@latest
          - eslint-config-standard@latest
        files: \.[jt]sx?$
        id: eslint
        types:
          - file
    repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.26.0
  - hooks:
      - id: prettier
        types_or:
          - css
          - javascript
          - jsx
          - tsx
          - ts
          - html
          - markdown
          - scss
          - yaml
          - gitignore
          - toml
    repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.3
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.35.0
